import type {
  BackgroundDefinition,
  BackgroundOptions,
  ShaderUniformDefinition,
} from "../types";
export const uniformControls: ShaderUniformDefinition[] = [
  { key: "motion", label: "Motion", min: 0, max: 2, step: 0.01 },
  { key: "scale", label: "Scale", min: 0.4, max: 3, step: 0.01 },
  { key: "warp", label: "Warp", min: 0, max: 2, step: 0.01 },
  { key: "warpScale", label: "Warp scale", min: 0.3, max: 5, step: 0.01 },
  { key: "distortion", label: "Distortion", min: 0, max: 2, step: 0.01 },
  { key: "noise", label: "Noise", min: 0, max: 1, step: 0.01 },
  { key: "noiseScale", label: "Noise scale", min: 0.5, max: 8, step: 0.01 },
  { key: "direction", label: "Direction", min: 0, max: 6.28, step: 0.01 },
  { key: "grain", label: "Grain", min: 0, max: 0.18, step: 0.001 },
  { key: "softness", label: "Softness", min: 0, max: 1, step: 0.01 },
  { key: "seed", label: "Seed", min: 0, max: 100, step: 1 },
  { key: "contrast", label: "Contrast", min: 0.5, max: 1.8, step: 0.01 },
  { key: "luminosity", label: "Luminosity", min: -0.3, max: 0.3, step: 0.01 },
  { key: "saturation", label: "Saturation", min: 0, max: 1.5, step: 0.01 },
  { key: "intensity", label: "Effect intensity", min: 0, max: 2, step: 0.01 },
];
export const baseUniforms: BackgroundOptions = {
  palette: ["#1b333b", "#d38a6c", "#f1c29b", "#ddd8b9", "#a9b49e"],
  motion: 0.45,
  scale: 1,
  noise: 0.15,
  grain: 0.035,
  seed: 12,
  warp: 0.45,
  warpScale: 1,
  distortion: 0.3,
  noiseScale: 2,
  direction: 0,
  softness: 0.45,
  contrast: 1,
  luminosity: 0,
  saturation: 1,
  intensity: 1,
  interpolation: 1,
};
export const makeBackground = (
  id: string,
  name: string,
  family: string,
  algorithm: string,
  palette: string[],
  options: Partial<BackgroundOptions> = {},
): BackgroundDefinition => ({
  id,
  name,
  family,
  algorithm,
  fragmentShader: algorithm,
  defaultUniforms: { ...baseUniforms, ...options, palette },
  customizableUniforms: uniformControls,
  suggestedClockColors: ["#fffaf0", "#272923"],
  previewImage: `/posters/${id}.webp`,
  premium: !["apricity", "silk", "tidal"].includes(id),
  reducedMotionFallback: `/posters/${id}.webp`,
});
export const backgrounds: BackgroundDefinition[] = [
  makeBackground(
    "chroma",
    "Chroma",
    "Soft",
    "chroma",
    ["#7859f4", "#ff86ef", "#ebacff", "#ff68ca"],
    { seed: 0, grain: 0.006, noise: 0, warp: 0, distortion: 0, motion: 0.45 },
  ),
  makeBackground(
    "relay",
    "Relay",
    "Graphic",
    "relay",
    ["#ff315c", "#fc86b5", "#2241f2", "#7388ff", "#271337"],
    { seed: 0, grain: 0.004, noise: 0, warp: 0, distortion: 0, motion: 0.35 },
  ),
  makeBackground(
    "corona",
    "Corona",
    "Sculptural",
    "corona",
    [
      "#fafaff",
      "#ffff95",
      "#fd5d18",
      "#272739",
      "#3e22a6",
      "#94b337",
      "#7af9ff",
      "#ffffff",
    ],
    {
      seed: 0,
      grain: 0.012,
      noise: 0,
      warp: 0,
      distortion: 0,
      motion: 0.25,
      softness: 0.4,
    },
  ),
  makeBackground(
    "spectrum",
    "Spectrum",
    "Sculptural",
    "spectrum",
    [
      "#f3efea",
      "#075640",
      "#048fa8",
      "#6295eb",
      "#e7badd",
      "#ffcb41",
      "#ff6711",
      "#bb331d",
    ],
    { seed: 0, grain: 0.004, noise: 0, warp: 0, distortion: 0, motion: 0.35 },
  ),
  makeBackground(
    "flux",
    "Flux",
    "Organic",
    "flux",
    [
      "#ff5a05",
      "#ff6a75",
      "#fb44b0",
      "#ce57e9",
      "#45c7ed",
      "#06bfee",
      "#ff631d",
    ],
    { seed: 0, grain: 0.006, noise: 0, warp: 0, distortion: 0, motion: 0.35 },
  ),
  makeBackground(
    "cobalt",
    "Cobalt",
    "Soft",
    "cobalt",
    ["#10129d", "#f1a692", "#c65fba", "#2559df"],
    { seed: 0, grain: 0.045, noise: 0, warp: 0, distortion: 0, motion: 0.4 },
  ),
  makeBackground(
    "abyss",
    "Abyss",
    "Atmospheric",
    "abyss",
    ["#060a24", "#096087", "#aec2c3", "#103154"],
    { seed: 0, grain: 0.01, noise: 0, warp: 0, distortion: 0, motion: 0.4 },
  ),
  makeBackground(
    "sundial",
    "Sundial",
    "Graphic",
    "sundial",
    ["#fafcff", "#3279ff", "#abc8ff", "#dfeaff"],
    { seed: 0, grain: 0.003, noise: 0, warp: 0, distortion: 0, motion: 0.2 },
  ),
  makeBackground(
    "isoline",
    "Isoline",
    "Quiet",
    "isoline",
    ["#030404", "#939093", "#ffffff", "#111111"],
    { seed: 0, grain: 0, noise: 0, warp: 0, distortion: 0, motion: 0.3 },
  ),
  makeBackground(
    "terrace",
    "Terrace",
    "Graphic",
    "terrace",
    ["#034438", "#065247", "#0862ab", "#215ca4", "#9d625e", "#ff6900"],
    { seed: 0, grain: 0.004, noise: 0, warp: 0, distortion: 0, motion: 0.3 },
  ),
  makeBackground(
    "lilt",
    "Lilt",
    "Organic",
    "lilt",
    [
      "#fff1bf",
      "#f591a3",
      "#f47158",
      "#1a91d1",
      "#92c4e0",
      "#f4d9e4",
      "#fdf9f1",
    ],
    { seed: 0, grain: 0.006, noise: 0, warp: 0, distortion: 0, motion: 0.3 },
  ),
  makeBackground(
    "weave",
    "Weave",
    "Sculptural",
    "weave",
    ["#074d67", "#4b96b1", "#aed4d9", "#598eab", "#c9dce2"],
    { seed: 0, grain: 0.009, noise: 0, warp: 0, distortion: 0, motion: 0.3 },
  ),
  makeBackground("apricity", "Apricity", "Soft", "mesh", [
    "#233d48",
    "#b77b68",
    "#efb894",
    "#edc7a2",
    "#b9bcaa",
  ]),
  makeBackground(
    "silk",
    "Silk",
    "Sculptural",
    "ribbon",
    ["#e8e6d7", "#17372e", "#698276", "#c3c394", "#d89965"],
    { grain: 0.018 },
  ),
  makeBackground(
    "tidal",
    "Tidal",
    "Atmospheric",
    "caustics",
    ["#102f43", "#315f70", "#95c8c0", "#d7e1cc", "#45677b"],
    { scale: 0.8 },
  ),
  makeBackground("vesper", "Vesper", "Soft", "wave", [
    "#242535",
    "#626181",
    "#b0a2b7",
    "#e0c5b3",
    "#53536b",
  ]),
  makeBackground("bloom", "Bloom", "Organic", "fluid", [
    "#471a25",
    "#ad4b4f",
    "#e38e77",
    "#edc499",
    "#804657",
  ]),
  makeBackground("boreal", "Boreal", "Atmospheric", "aurora", [
    "#101f20",
    "#27493b",
    "#88af73",
    "#c9d7a4",
    "#32566b",
  ]),
  makeBackground("haze", "Haze", "Atmospheric", "fog", [
    "#363d42",
    "#aeb4a0",
    "#e6c8ac",
    "#d1a088",
    "#657b7b",
  ]),
  makeBackground("overcast", "Overcast", "Atmospheric", "clouds", [
    "#252e3e",
    "#56677a",
    "#a9b4b9",
    "#e3ded0",
    "#7d8c98",
  ]),
  makeBackground("drift", "Drift", "Organic", "perlin", [
    "#eee4c9",
    "#cfaa94",
    "#7a8a83",
    "#b8b4a0",
    "#dfc9ae",
  ]),
  makeBackground("strata", "Strata", "Graphic", "bands", [
    "#3b4436",
    "#8d9167",
    "#d1b67c",
    "#dca273",
    "#a06346",
  ]),
  makeBackground("nectar", "Nectar", "Organic", "blobs", [
    "#391f30",
    "#835265",
    "#d99a86",
    "#e4c4a4",
    "#a36e79",
  ]),
  makeBackground("pebble", "Pebble", "Organic", "metaballs", [
    "#d9d8c9",
    "#636e62",
    "#92967f",
    "#e9e6d7",
    "#b9ab88",
  ]),
  makeBackground("prism", "Prism", "Sculptural", "glass", [
    "#272b3f",
    "#596383",
    "#a7a7c4",
    "#d0bcc2",
    "#7e8f9f",
  ]),
  makeBackground("spectral", "Spectral", "Sculptural", "refraction", [
    "#161c22",
    "#768080",
    "#ccd5cd",
    "#b99379",
    "#ecede1",
  ]),
  makeBackground("iris", "Iris", "Sculptural", "lens", [
    "#d5ddc7",
    "#788d6e",
    "#233f35",
    "#d4b685",
    "#8eaa9a",
  ]),
  makeBackground("opal", "Opal", "Sculptural", "iridescent", [
    "#4b5b61",
    "#a4b4ac",
    "#dcc6b2",
    "#bca4ba",
    "#7d8fa8",
  ]),
  makeBackground(
    "sienna",
    "Sienna",
    "Soft",
    "editorial",
    ["#58392f", "#9d5e44", "#d29f7a", "#e3c1a0", "#aa896a"],
    { grain: 0.1 },
  ),
  makeBackground("cutout", "Cutout", "Graphic", "poster", [
    "#e6ddc5",
    "#a7b9af",
    "#4d6d7d",
    "#2c434c",
    "#d9a075",
  ]),
  makeBackground(
    "riso",
    "Riso",
    "Graphic",
    "halftone",
    ["#e2cc90", "#404736", "#999763", "#d2b97c", "#6f7651"],
    { grain: 0.06 },
  ),
  makeBackground(
    "signal",
    "Signal",
    "Graphic",
    "dots",
    ["#000000", "#666666", "#ffffff", "#dddddd", "#333333"],
    { grain: 0, noise: 0, warp: 0, distortion: 0 },
  ),
  makeBackground(
    "static",
    "Static",
    "Quiet",
    "noise",
    ["#151918", "#596059", "#bbc0b4", "#e0e1d4", "#6e766b"],
    { grain: 0.1 },
  ),
  makeBackground("atlas", "Atlas", "Graphic", "contours", [
    "#d7ceb3",
    "#7b8165",
    "#394d43",
    "#a5a184",
    "#58674f",
  ]),
  makeBackground("current", "Current", "Graphic", "lines", [
    "#16312f",
    "#386762",
    "#93b0a1",
    "#d0d1b5",
    "#577f75",
  ]),
  makeBackground("afterglow", "Afterglow", "Soft", "diffusion", [
    "#261b2b",
    "#743d39",
    "#ce7752",
    "#edb07c",
    "#683f58",
  ]),
  makeBackground("gyre", "Gyre", "Sculptural", "rotation", [
    "#322629",
    "#794445",
    "#cb8b6b",
    "#e5b99b",
    "#60444d",
  ]),
  makeBackground("quiet", "Quiet", "Quiet", "monochrome", [
    "#202922",
    "#505b4b",
    "#a9af97",
    "#d1d3bd",
    "#77806b",
  ]),
  makeBackground("halo", "Halo", "Atmospheric", "atmosphere", [
    "#222d29",
    "#5f7752",
    "#a6b681",
    "#d8dbb6",
    "#74897a",
  ]),
  makeBackground("pigment", "Pigment", "Organic", "paint", [
    "#ebe0c9",
    "#b27753",
    "#355a63",
    "#7c9a8b",
    "#cea37b",
  ]),
  ...[
    ["paper", "Paper", "#f9f9f7"],
    ["ink", "Ink", "#171819"],
    ["butter", "Butter", "#f3edc9"],
    ["lilac", "Lilac", "#e6deef"],
    ["coast", "Coast", "#16434b"],
  ].map(([id, name, color]) => ({
    ...makeBackground(
      id,
      name,
      "Essentials",
      "chroma",
      [color, color, color, color],
      { motion: 0 },
    ),
    premium: false,
    customizableUniforms: [],
    suggestedClockColors: ["ink", "coast"].includes(id)
      ? ["#fffaf0", "#272923"]
      : ["#272923", "#fffaf0"],
    staticBackground:
      id === "coast"
        ? 'linear-gradient(#001d2918, #001d2938), url("/images/coast.png") center / cover'
        : color,
    previewImage: id === "coast" ? "/images/coast.png" : "",
    reducedMotionFallback: id === "coast" ? "/images/coast.png" : "",
  })),
];
for (const b of backgrounds)
  if (
    [
      "silk",
      "drift",
      "pebble",
      "iris",
      "cutout",
      "riso",
      "atlas",
      "pigment",
      "spectrum",
      "sundial",
      "lilt",
    ].includes(b.id)
  )
    b.suggestedClockColors = ["#272923", "#fffaf0"];
export const backgroundById = (id: string) =>
  backgrounds.find((b) => b.id === id) ?? backgrounds[0];
const shaderBackgroundStyle = (id: string, palette: string[]) => ({
  backgroundColor: palette[0],
  backgroundImage: `url(/posters/${id}.webp), radial-gradient(ellipse at 62% 15%, ${palette[3]} 0%, transparent 67%), radial-gradient(ellipse at 80% 95%, ${palette[1]} 0%, transparent 65%), linear-gradient(125deg, ${palette[0]}, ${palette[2]})`,
});

export const backgroundStyle = (id: string) => {
  const def = backgroundById(id);
  if (def.staticBackground) return { background: def.staticBackground };
  return shaderBackgroundStyle(id, def.defaultUniforms.palette);
};

export const backgroundStyleForPreset = (preset: {
  backgroundId: string;
  backgroundOptions?: Partial<BackgroundOptions>;
}) => {
  const def = backgroundById(preset.backgroundId);
  if (def.staticBackground) return backgroundStyle(preset.backgroundId);
  const palette =
    preset.backgroundOptions?.palette ?? def.defaultUniforms.palette;
  return shaderBackgroundStyle(preset.backgroundId, palette);
};
